apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-management-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: secret-management-operator
  template:
    metadata:
      labels:
        name: secret-management-operator
    spec:
      containers:
        - name: secret-management-operator
          image: local
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - secret-management-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "secret-management-operator"
