---
apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: Role
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      name: secret-management-operator
    rules:
    - apiGroups:
      - secret.management.operator
      resources:
      - "*"
      verbs:
      - "*"
    - apiGroups:
      - ""
      resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      verbs:
      - "*"
    - apiGroups:
      - apps
      resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      verbs:
      - "*"
  - apiVersion: v1
    kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1beta1
    metadata:
      name: default-account-secret-management-operator
    subjects:
    - kind: ServiceAccount
      name: default
      namespace: secret-operator
    roleRef:
      kind: Role
      name: secret-management-operator
      apiGroup: rbac.authorization.k8s.io